import { Inter } from "next/font/google";
import "@/helpers/reset.scss";
import { Providers } from "@/lib/StoreProvider";
import { Header } from "@/components";
import { AdminAllCategories } from "@/components/admin";

import './layout.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Project admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className="container fluid admin_page admin_total">
        <Providers>
          <Header />
          <main className="all_Products fluid">
            <AdminAllCategories />
            {children}
          </main>
        </Providers>
      </div>
  );
}
