import { Inter } from "next/font/google";
import "@/helpers/reset.scss";
import { Providers } from "@/lib/StoreProvider";
import '../../helpers/reset.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Project admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children } ) {
  return (
    <html lang="en">
      <body className={`${inter.className} container`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
